name: 🎪 Staging Deploy

on:
  push:
    branches:
      - 'main'
    paths:
        - '**.ts'
        - '**.js'
        - '**.css'
        - '**.hbs'

env:
  ENVIRONMENT: PRODUCTION

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: 👯‍♂️ Clone Repository
        uses: actions/checkout@v4
      - name: 🦕 Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: 🔎 Inspect
        run: deno run --allow-all main.ts